name: Build, test and publish dotnet
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      code-quality: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.x
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Check formatting
        run: dotnet format --verify-no-changes
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release --coverlet --coverlet-output-format cobertura
      - name: Install report generator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Pack the project
        run: dotnet pack --configuration Release
      - name: Generate coverage report
        run: reportgenerator -reporttypes:"MarkdownSummary;Cobertura" -reports:**/coverage.cobertura*.xml -targetdir:./reports/coverage
      - name: Upload coverage report
        if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') || (github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch)
        uses: actions/upload-code-coverage@v1
        with:
          file: reports/coverage/Cobertura.xml
          language: CSharp
          label: code-coverage/dotnet
      - uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: reports/coverage
      - uses: actions/upload-artifact@v7
        with:
          name: packages
          path: src/*/bin/Release/*.*nupkg
      - name:  Publish coverage report to GitHub Step Summary
        run: |
           cat reports/coverage/Summary.md >>  $GITHUB_STEP_SUMMARY

  validate-performance:
    name: Validate performance of the library
    runs-on: ubuntu-latest
    needs: [dotnet-build]
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - name: Copy committed results
        run: |
          mkdir -p ./performanceResults
          cp -r ./performance/benchmark/BenchmarkDotNet.Artifacts/results/* ./performanceResults
      - name: Run performance tests
        run: dotnet run -c Release
        working-directory: ./performance/benchmark
      - name: Publish benchmark results
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: benchmark-results
          path: ${{ github.workspace }}/performance/benchmark/BenchmarkDotNet.Artifacts/results
      - name: Run comparison tool for empty models
        run: dotnet run -c Release --project ./performance/resultsComparer/resultsComparer.csproj -- compare $OLD_REPORT $NEW_REPORT -p IdenticalMemoryUsage
        shell: bash
        env:
          NEW_REPORT: ${{ github.workspace }}/performance/benchmark/BenchmarkDotNet.Artifacts/results/performance.EmptyModels-report.json
          OLD_REPORT: ${{ github.workspace }}/performanceResults/performance.EmptyModels-report.json
      - name: Run comparison tool for descriptions
        run: dotnet run -c Release --project ./performance/resultsComparer/resultsComparer.csproj -- compare $OLD_REPORT $NEW_REPORT -p ZeroPointTwoPercentDifferenceMemoryUsage
        shell: bash
        env:
          NEW_REPORT: ${{ github.workspace }}/performance/benchmark/BenchmarkDotNet.Artifacts/results/performance.Descriptions-report.json
          OLD_REPORT: ${{ github.workspace }}/performanceResults/performance.Descriptions-report.json

  publish-release-to-nuget:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: dotnet-build
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.x
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
      - name: Download packages
        uses: actions/download-artifact@v8
        with:
          name: packages
      - name: NuGet login
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish to NuGet
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
      - name: Publish to GitHub Packages
        run: gh release upload ${{ github.ref_name }} lib/bin/Release/*.nupkg lib/bin/Release/*.snupkg tool/bin/Release/*.nupkg tool/bin/Release/*.snupkg --repo ${{ github.repository }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
